# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - pom.xml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - pom.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven

      - name: Store short hash and branch name
        id: git-details
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn -DfinalName="MagicMOTD DEV ${{ steps.git-details.outputs.branch }}@${{ steps.git-details.outputs.sha }}" -B package --file pom.xml

      - uses: actions/upload-artifact@v3
        with:
          name: MagicMOTD DEV JAR
          path: "target/GunFrame DEV ${{ steps.git-details.outputs.branch }}@${{ steps.git-details.outputs.sha }}.jar"


      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
